name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies for BlackjackAPI
        run: dotnet restore
        working-directory: ./BlackjackAPI/BlackjackAPI

      - name: Restore dependencies for BlackjackService
        run: dotnet restore
        working-directory: ./BlackjackService/BlackjackService

      - name: Create .env for BlackjackAPI
        run: |
          Remove-Item -Path ./BlackjackAPI/BlackjackAPI/.env -ErrorAction Ignore
          echo "DB_SERVER=${{ secrets.DB_SERVER }}" >> ./BlackjackAPI/BlackjackAPI/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> ./BlackjackAPI/BlackjackAPI/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ./BlackjackAPI/BlackjackAPI/.env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> ./BlackjackAPI/BlackjackAPI/.env

          echo "JWT=${{ secrets.JWT }}" >> ./BlackjackAPI/BlackjackAPI/.env
 
      - name: Create .env for BlackjackService
        run: |
          Remove-Item -Path ./BlackjackService/BlackjackService/.env -ErrorAction Ignore
          echo "DB_SERVER=${{ secrets.DB_SERVER }}" >> ./BlackjackService/BlackjackService/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> ./BlackjackService/BlackjackService/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ./BlackjackService/BlackjackService/.env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> ./BlackjackService/BlackjackService/.env

          echo "WS_URL=wss://wsi532747.luna.fhict.nl/ws/" >> ./BlackjackService/BlackjackService/.env
          echo "JWT=${{ secrets.JWT }}" >> ./BlackjackService/BlackjackService/.env

      # Debugging
      - name: Check BlackjackAPI .env contents
        run: cat ./BlackjackAPI/BlackjackAPI/.env
	
      # Debugging
      - name: Check BlackjackService .env contents
        run: cat ./BlackjackService/BlackjackService/.env

      - name: Publish BlackjackAPI
        run: dotnet publish -c Release -o ${{ github.workspace }}/publish/BlackjackAPI
        working-directory: ./BlackjackAPI/BlackjackAPI

      - name: Publish BlackjackService
        run: dotnet publish -c Release -o ${{ github.workspace }}/publish/BlackjackService
        working-directory: ./BlackjackService/BlackjackService

      - name: Deploy BlackjackAPI to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          protocol: ftps
          server: 145.85.4.100
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ${{ github.workspace }}/publish/BlackjackAPI
          server-dir: /domains/apii532747.luna.fhict.nl/
          dangerous-clean-slate: true
          passive: true

      - name: Deploy BlackjackService to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          protocol: ftps
          server: 145.85.4.100
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ${{ github.workspace }}/publish/BlackjackService
          server-dir: /domains/wsi532747.luna.fhict.nl/
          dangerous-clean-slate: true
          passive: true
