# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI - Testing & Code Analyzers

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: List files for debugging
      run: ls -R 
      
    - name: Restore dependencies
      run: dotnet restore BlackjackAPI/BlackjackRoyale.sln
      
    - name: Build
      run: dotnet build BlackjackAPI/BlackjackRoyale.sln --no-restore
      
    - name: Test
      run: dotnet test BlackjackAPI/BlackjackRoyale.sln --no-build --verbosity normal

    - name: Run Roslyn Analyzers
      run: |
        dotnet build BlackjackAPI/BlackjackRoyale.sln --configuration Release
        dotnet build BlackjackAPI/BlackjackRoyale.sln --configuration Release /p:RunAnalyzers=true

    # .net format to check code style and formatting, fail on issues
    - name: Run .NET Format
      run: |
        dotnet format BlackjackAPI/BlackjackRoyale.sln --verbosity normal
        if [ $? -ne 0 ]; then
          echo "Formatting issues found! Please run 'dotnet format' to fix.";
          exit 1;
        fi
        
    # run stylecop analyzers
    - name: Run StyleCop Analyzers
      run: |
        dotnet build BlackjackAPI/BlackjackRoyale.sln --configuration Release
        dotnet stylecop analyze
